// starters/vue-ts/src/App.vue
<script setup lang="ts">
import NimiqDemo from './components/NimiqDemo.vue'
</script>

<template>
  <div class="container-fluid" style="max-width: 500px; margin: 0 auto; padding: 1rem;">
    <hgroup style="text-align: center; margin-bottom: 1.5rem;">
      <h3>Nimiq Vue Starter</h3>
      <p><small>Nimiq web client integration demo</small></p>
    </hgroup>

    <NimiqDemo />
  </div>
</template>

// starters/react-ts/src/App.tsx
import { NimiqDemo } from './components/NimiqDemo'

function App() {
  return (
    <div className="container-fluid" style={{ maxWidth: '500px', margin: '0 auto', padding: '1rem' }}>
      <hgroup style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
        <h3>Nimiq React Starter</h3>
        <p><small>Nimiq web client integration demo</small></p>
      </hgroup>

      <NimiqDemo />
    </div>
  )
}

export default App
