// starters/vue-ts/src/components/NimiqDemo.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useNimiq } from '../composables/useNimiq'

const { client, loading, error, consensus, headBlockNumber, initializeNimiq } = useNimiq()

const isConnected = computed(() => client.value !== null)
const buttonText = computed(() => isConnected.value ? 'Connected' : 'Connect to Nimiq')
</script>

<template>
  <main class="container">
    <article>
      <div style="text-align: center; margin-bottom: 2rem;">
        <button
          :disabled="loading || isConnected"
          :aria-busy="loading"
          @click="initializeNimiq"
        >
          {{ buttonText }}
        </button>
      </div>

      <div v-if="error" role="alert">
        <strong>Error:</strong> {{ error }}
      </div>

      <div v-if="isConnected" style="text-align: center;">
        <p><strong>✓ Connected</strong></p>
        <p><kbd>{{ consensus }}</kbd> • Block <code>{{ headBlockNumber }}</code></p>
      </div>
    </article>
  </main>
</template>

// starters/nextjs/components/NimiqDemo.tsx
'use client'

import { useMemo } from 'react'
import { useNimiq } from '@/hooks/useNimiq'

export default function NimiqDemo() {
  const { client, loading, error, consensus, headBlockNumber, initializeNimiq } = useNimiq()

  const isConnected = useMemo(() => client !== null, [client])
  const buttonText = useMemo(() => isConnected ? 'Connected' : 'Connect to Nimiq', [isConnected])

  return (
    <main className="container">
      <article>
        <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
          <button
            disabled={loading || isConnected}
            aria-busy={loading}
            onClick={initializeNimiq}
          >
            {buttonText}
          </button>
        </div>

        {error && (
          <div role="alert">
            <strong>Error:</strong>
            {' '}
            {error}
          </div>
        )}

        {isConnected && (
          <div style={{ textAlign: 'center' }}>
            <p>
              <strong>✓ Connected</strong>
            </p>
            <p>
              <kbd>{consensus}</kbd>
              {' • Block '}
              <code>{headBlockNumber}</code>
            </p>
          </div>
        )}
      </article>
    </main>
  )
}
